storeItemList:
  - id: '16967417967810.8748230808963213'
    name: filterdata
    value: {}
    valueType: object
    initialValue: {}
    version: 1
  - id: '16993215486990.1856650249075653'
    name: selectedcafetransactrion
    value: {}
    valueType: object
    initialValue: {}
    version: 1
  - id: '16993215622220.726899203234955'
    name: selectedcafeinfo
    value: {}
    valueType: object
    initialValue: {}
    version: 1
metadata:
  favicon: ''
  code: |-
    <style>
    .fixed-width {
       width: 150px; !important;
       max-width: 250px; !important;
    }
    .logo {
    color: green;
      }
    </style>
  title: Hubs VN App
  description: ''
  breakpoints: []
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: default
internalType: project
